# Generated by Django 3.2.5 on 2021-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
