# Generated by Django 3.2.5 on 2021-07-11 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_sampledetail_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledetail',
            name='phone',
            field=models.CharField(default='', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Ensure Phone number must be 10 digits: EX: '9999999999'.", regex='^(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??)')]),
        ),
    ]
